### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by tuqiangwang** [alexandru-dinu/cae#5]
Traceback (most recent call last):
  File "train.py", line 94, in <module>
    train(args)
  File "train.py", line 36, in train
    for bi, (img, patches, _) in enumerate(dataloader):
  File "/home/tq/anaconda3/envs/p3.6torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/tq/anaconda3/envs/p3.6torch0.4.1/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 314, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/tq/nets/cae/image_folder.py", line 20, in __getitem__
    h, w, c = img.shape[:3] #delete [:3]
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by alexandru-dinu** [comment]
It seems that your image only has 2 dimensions (h, w). Are you using grayscale images?
